### ISSUE TITLE
[Feature Request] Background Image

### ISSUE THREAD

**Issue by prouderthings** [bastienwirtz/homer#104]
Awesome work!

One thing I would love is a way to define a full background image instead of a color.  If there is a way I can hack this in there please let me know!

Everything else is spot on!

**Comment by Shuro** [comment]
Fork the default theme, found in `src/assets/themes`, fiddle with it and use your new theme in your config file.

**Comment by bastienwirtz** [comment]
Hi there! 

Thanks @prouderthings! Like @Shuro said, it's possible by using theme, but I think I will add it as an option in the `config.yml` to make it simplier in the near future. I'll keep you updated!

**Comment by bastienwirtz** [comment]
There you go : https://github.com/bastienwirtz/homer/commit/154e6efe8036dca91b1bfe9c4fb22ef227df5858 !

You can use the a new `background-image` option in the `colors` config section. Check out the [doc](https://github.com/bastienwirtz/homer/blob/master/docs/configuration.md) for more information. 

You can define **2 background images**, for light and dark theme (of course you can put the same for both if you like). 

![Peek 2020-07-15 14-22](https://user-images.githubusercontent.com/345559/87599173-4bfe8c00-c6a8-11ea-976f-51ea21476303.gif)


I applied the background to the main section (header excluded), but maybe I could include the header? (technically you can set the header color to `transparent` or apply some opacity, so the top would be empty without wallpaper). 

Anyway, let me know what you think!

**Comment by prouderthings** [comment]
Wow that was really fast!  I never finished trying to do this with a theme. The implementation is fantastic!  

Not sure if this is solely related to my setup (unraid), but the image location had to be "../assets/your/light/bg.png". I noticed it was defaulting to the "/css/bg.png" directory so I added the ../ and that fixed it.   Again, this might be my setup as docker on unraid can be funny sometimes.

My two cents on the header, when I set my background, I also set a rgba() value for the header color and was able to see the background behind it just fine.  Honestly I think this is great!

PS, I noticed the logo does not show up with the default config from the docs.  It's looking for assets/homer.png, but I changed it to logo.png as I noticed it was outside of assets.  Again, this might be because I'm using unraid and have something configured wrong.

**Comment by bastienwirtz** [comment]
Thanks for the feedback @prouderthings!
I'll look into the location url more in detail and update the documentation as needed. And nice catch for the logo, I will update that too!

I'm closing the issue, but feel free to reopen it if anything!

**Comment by polhaghverdian** [comment]
> 
> 
> Wow that was really fast! I never finished trying to do this with a theme. The implementation is fantastic!
> 
> Not sure if this is solely related to my setup (unraid), but the image location had to be "../assets/your/light/bg.png". I noticed it was defaulting to the "/css/bg.png" directory so I added the ../ and that fixed it. Again, this might be my setup as docker on unraid can be funny sometimes.
> 
> My two cents on the header, when I set my background, I also set a rgba() value for the header color and was able to see the background behind it just fine. Honestly I think this is great!
> 
> PS, I noticed the logo does not show up with the default config from the docs. It's looking for assets/homer.png, but I changed it to logo.png as I noticed it was outside of assets. Again, this might be because I'm using unraid and have something configured wrong.

Same issue using docker.

**Comment by PixelDJ** [comment]
Same issue here. Using docker on Unraid.

Regular service images work fine as
`logo: "assets/tools/dell.png"`

But in the colors section I had to use the following to get to my wallpaper:
`background-image: "../assets/images/bg-darkblue.png"`

Can we re-open this until there is a fix (or documentation updated with the workaround)? It was difficult for me to find a solution until I started digging through closed issues.

Otherwise I want to say thank you so much for your hard work on this project. I recently switched from Heimdall and homer is working amazingly. If I was a little better at coding I would love to contribute.

Side note: If anyone needs service logos check my repo  (forked from NX211's homer icons repo).

**Comment by ThatAnonyG** [comment]
Sorry if I am hijacking this issue, but recently I tried to set the background and put the image under the assets folder (my volume is at /home/user/homer). But since it was not loading I checked network logs and found out that homer is trying to find the image under `/resources`. I can use a relative path but that is a bit hacky.

**Comment by ihardyslide** [comment]
I have the same issue as @ThatAnonyG with the latest docker image on Debian Bullseye.
Funnily enough the old workaround with a relative path is still working.
