### ISSUE TITLE
[Feature] docker labels?

### ISSUE THREAD

**Issue by EsEnZeT** [bastienwirtz/homer#116]
I think it would be great if services could be configured via docker labels - example here: https://github.com/WillFantom/sui

**Comment by gabe565** [comment]
That's a cool looking example! I'll have to check out how SUI is using labels more.

Unfortunately, this project currently builds into static assets during the Docker build so any sort of dynamic configuration like this isn't possible without pretty big underlying changes. A script could be written which takes labels and generates a `config.yml`, but that wouldn't be as pretty of an integration as the example you linked (Which has a running process that generates the page based on the labels on request).

Another point to keep in mind, to view the Docker labels that are set requires passing `/var/run/docker.sock` into the container. This is pretty dangerous security-wise since Docker's API usually has root access to the hosting server.

I'd be curious to know @bastienwirtz's opinion on this.

**Comment by bwirtz** [comment]
Hi there!
Sorry for the lack of reactivity. 
That would be nice, but as mentioned by @gabe565, Homer is just a simple static site and aim to stay this way. I really wanted to build something very low maintenance & really easy setup and requirements.

**Comment by bastienwirtz** [comment]
Hi there!
Sorry for the lack of reactivity.
That would be nice, but as mentioned by @gabe565, Homer is just a simple static site and aim to stay this way. I really wanted to build something very low maintenance & really easy setup and requirements.
Thanks anyway for the suggestion @EsEnZeT, appreciated!

**Comment by danielpetroianu** [comment]
I wanted this feature as well in Homer. 
Because I like how Homer looks, and don't want to use WillFantom/sui or pawelmalak/flame or ..., I've written a small bash script that updates the config.yml 
See it her https://gist.github.com/danielpetroianu/6e00624436eab3036b0c8b270b359b62

Posting this here, just in case someone googles about this and ends up here (like me). 
Hope it's helpful.

**Comment by thomas-mc-work** [comment]
> Homer is just a simple static site and aim to stay this way. I really wanted to build something very low maintenance & really easy setup and requirements.

What do you think about a label based discovery on build time? Still leverages the benefits of having the configuration next to the container definitions AND finally building a static site?

**Comment by zotabee** [comment]
Check this: https://github.com/bastienwirtz/homer/issues/445#issuecomment-3831964766

https://github.com/pro-tweaker/homer-service-discovery

**Comment by NikitaMikhailov** [comment]
I built a small external CLI for exactly this reason. Homer stays the simple static site it's meant to be, no daemon inside it. dashsync reads dashsync.* labels off your containers and writes/updates Homer's config.yml directly (idempotent, keeps your hand edits). Same labels also work for Homepage and Dashy if you use those elsewhere.

https://github.com/NikitaMikhailov/dashsync
