### ISSUE TITLE
CORS request require http or https protocol (app.js)

### ISSUE THREAD

**Issue by managai** [bastienwirtz/homer#14]
Hi,
I just downloaded zip archive, uncompressed it in folder and opened browser (firefox 72 and chromium 79) via file protocol

file:///$PATHTO/homer/index.html

both browser fail to open page and return a CORS related error located at
app.js:48
app.js:58

in firefox (68+) resing reason error is described at https://developer.mozilla.org/it/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

some idea how to fix issue without having to edit browser settings ?

**Comment by odin-bb** [comment]
I am having the same issue. I am wondering if you need to put this on a server to have the apache/nginx engine to get it to work. I will attempt that this weekend.

**Comment by odin-bb** [comment]
> Hi,
> I just downloaded zip archive, uncompressed it in folder and opened browser (firefox 72 and chromium 79) via file protocol
> 
> file:///$PATHTO/homer/index.html
> 
> both browser fail to open page and return a CORS related error located at
> app.js:48
> app.js:58
> 
> in firefox (68+) resing reason error is described at https://developer.mozilla.org/it/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp
> 
> some idea how to fix issue without having to edit browser settings ?

Hey so running the homer on a apache2 server worked perfectly. I think that is what it meant. You'll have to create a virtual host to get it to work, but that is how I got it to work. 

If you need some help with that I can help. Shoot me a message. 

If you are trying to get it to work locally, I'd wait on him to respond.

**Comment by traeblain** [comment]
Line 48 makes an HTTP HEAD request and line 58 is looking for an HTTP Status Code (i.e. 200).  When opening from a file:// the requests are FILE request not HTTP requests.  This is easily fixed by utilizing a simple HTTP server.

If you have python installed run in the directory:
```python -m http.server 8000```

If you would rather use node, then:
```npm install http-server -g```
then in the directory run:
```npx http-server -p 8000```

If you'd rather use PHP, then run in the directory:
```php -S 127.0.0.1:8000```

After all of these you just need to go to ```http://localhost:8000``` and it should work.

You can also look at these depending upon your editor:
[Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)
[SublimeText](https://packagecontrol.io/packages/SublimeServer)
[Atom Editor](https://atom.io/packages/atom-live-server)
[Brackets (Built-In)](http://brackets.io/)

Point is, you don't need apache/nginx/litespeed/caddy/etc. to dev this but do need something to handle HTTP requests.

**Comment by bastienwirtz** [comment]
Hi there, 
Sorry for answering so late! As mentioned by @traeblain you need to have something to serve the files, assets & handle the CORS request. I'm afraid there is not really other workaround to that.
