### ISSUE TITLE
Feature Request: Enable different 'pages' via multiple configs?

### ISSUE THREAD

**Issue by brandoncorry** [bastienwirtz/homer#152]
Was wondering if it would be possible to augment the getConfig function to take in a parameter from the URL to possibly load a different config (and default to config.yml)? This would enable you to have navigation links within the system to other pages.

**Comment by luixal** [comment]
Hi, I can help with this one. Do you wan to load a remote yaml file? or load data from a json? Maybe the second would make more sense.

**Comment by brandoncorry** [comment]
I was thinking something along the lines of just having multiple config.yml. So I could use the nav bar to have links to localhost/?p=page2, localhost/?p=page3 or whatever, and all it does is take that parameter and load that config.yml - that way I can have a home page, and then different pages for totally different things (i.e. have a page for the spouse, one for the kids, etc. that I could set as their homepages.)

**Comment by luixal** [comment]
That could be a good approach. Maybe having a correlation between the parameter value and the config file lodaded. This is, when going to `localhost?page=applications` it loads the `applications.yml` file.

I'll have a look at the code to see if it can be done without making big impact changes :)

**Comment by luixal** [comment]
Just added a PR that adds this feature. Examples are in the `assets/config.yml` and `assets/page2.yml` files, more info in the PR itself, as I don't found any structured docs where I can put this.

**Comment by jeff-h** [comment]
This is a little broken for me; when I load my second page, the group headings change correctly, and the number of items change correctly, but the service items themselves carry over from the previous page.

In other words, the second page displays the correct group headings, and the correct number of items, but the items themselves are all from the first page.

**Comment by jeff-h** [comment]
Whilst experimenting with the bug I did notice that the second page displays perfectly if I copy all its items into the first page.

**Comment by jeff-h** [comment]
I realised it happens only on horizontal layout mode.

I am getting the following in the console, when I click on my header link to the second page, and then also when I click back to the front page:

```
TypeError: Cannot read property 'key' of undefined
    at ji (vue.runtime.esm.js:5817)
    at C (vue.runtime.esm.js:6219)
    at E (vue.runtime.esm.js:6319)
    at C (vue.runtime.esm.js:6193)
    at E (vue.runtime.esm.js:6319)
    at C (vue.runtime.esm.js:6193)
    at E (vue.runtime.esm.js:6319)
    at C (vue.runtime.esm.js:6193)
    at E (vue.runtime.esm.js:6319)
    at C (vue.runtime.esm.js:6193)
```

[At this line](https://github.com/bastienwirtz/homer/blob/main/src/App.vue#L76) I tried replacing:

```vue
              <Service
                v-for="(item, index) in group.items"
                :key="index"
                v-bind:item="item"
                :class="['column', `is-${12 / config.columns}`]"
              />
```

with

```vue
              <Service
                v-for="item in group.items"
                :key="item"
                v-bind:item="item"
                :class="['column', `is-${12 / config.columns}`]"
              />
```

and the problem went away entirely. Unfortunately it's been years since I did any Vue, but I'm guessing my "fix" indicates a deeper issue with the preparation of the `group.items`.

**Comment by luixal** [comment]
Umm... quite curious.

**DISCLAIMER: ** this is just an idea of what can be happening, haven't really dug into it.

If the problem went away when you used the `item` object as key instead of the `index` it should point that there are kind of _"duplicates"_, this is, two elements using the same `key` which is used by Vue to handle this kind of stuff.

I guess the problem is somehow related to [this line](https://github.com/bastienwirtz/homer/blob/996011956b97566849167ccd6ec470ab38b0ec60/src/App.vue#L165):

```js
this.config = merge(defaults, config);
```
Method `buildDashboard` is called in two situations, once when App is created and then, when the `window` object changes. The latest is used for handling navigation to a different page. The first time the `merge` works well because there's no previous data, but the second time `items` form the `config` are merged keeping the older ones (that explains why items from previous page do not go away) and in some way a problem with indexes appear.

Maybe simply clearing `this.config.items` before the merge in `buildDashboard` would do the trick.

@jeff-h can you provide the config files you're using so I can have a look? If you can make a repo I can clone to reproduce the problem would be even better! :)

**Comment by jeff-h** [comment]
I reckon the two attached config files will hopefully replicate this pretty easily. I'll also put up a repo with the compiled `/dist` directory in case that's easier.

Really appreciate your time looking at this!

[infra-page.yml.txt](https://github.com/bastienwirtz/homer/files/6690280/infra-page.yml.txt)
[config.yml.txt](https://github.com/bastienwirtz/homer/files/6690281/config.yml.txt)

(Sorry, had to append `.txt` to these to get Github to attach them)

**Comment by luixal** [comment]
Hi  @jeff-h , I had some time today to try your config files and... no bug on my side, they work like a charm (items showed accordingly, no warn/error messages on the console... nothing weird).

I try then with a fresh clone of the master branch and then with a built version using just the dist folder (I used `npx serve` to serve it).

No idea why it isn't working on your side, I didn't change a char in your two files.

**Comment by jeff-h** [comment]
Hey, thanks for trying it. You definitely put it into horizontal layout mode then changed between the two pages ("Main" & "Infrastructure" in my demo)?

**Comment by luixal** [comment]
Hi!

That was it, I didn't try the horizontal view! The problem is easy to see (even Vue extension for vscode marks it), but it's not so straight forward to solve.

Vertical and horizontal views are coded quite differently. In the case of the vertical layout, this error does not happen because elements are wrapped in a `div` element and it has the `:key="group.name"` attribute so Vue can handle them nicely but, in the horizontal view everything is wrapped into a `template` element that doesn't allow you to use the `:key` attribute. Also, the use of `columns` doesn't seem appropiate (to me, maybe I'm not seeing something) in the horizontal layout.

The only way I see to solve this is re-writting the all the html code in the horizontal layout to get rid of this template element, but I'm not sure if it's needed for something.

What do you think @bastienwirtz ?

**Comment by luixal** [comment]
I finally put together a possible solution, @jeff-h you can try it out in the [PR linked above](https://github.com/bastienwirtz/homer/pull/241) :)

**Comment by jeff-h** [comment]
PR works flawlessly for me. Thanks so much for your work on this!

**Comment by luixal** [comment]
Great to hear that!

Let's wait for @bastienwirtz to review the PR and merge it if he finds the solution is ok along the rest of the project :)
