### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by joeczucha** [bastienwirtz/homer#162]
I've been randomly getting a strange error in Firefox

> Request Entity Too Large
> Your request was dropped because it was too long. 
> Generated by darkhttpd/1.12 on Tue, 17 Nov 2020 16:23:40 GMT 

It seems to just arise out-of-the-blue, without any recent changes having been made and when it's been working just fine moments before! Clearing the browser cache seems to fix it, but it's annoying :) 

Has anyone else experienced this? Thanks!

**Comment by ungol-fr** [comment]
Hello, 
I have the same problem, and I use Keycloak Gatekeeper as an authentication proxy. I tried to make requests lighter, removing infos from token and I succeeded to go from a totally unreachable server (with 413 Request Entity Too Large error) to a most-of-the-time reachable one. When it does not work, restart Firefox or open a new tab seems to work. Without Gatekeeper however, my Homer is perfectly working but I would prefer not to expose it directly.
This problem is also present on qutebrowser. I did not try with any other browser.

Maybe darkhttpd does not support too large headers ? I did not find any option in documentation to tune this.

If anyone has experienced this and/or more info, you're very welcome ! Thank you

**Comment by MarkNjunge** [comment]
In my case, I had a large cookie [set by Deluge](https://dev.deluge-torrent.org/ticket/2894). Deleting it resolved the issue. However, it's likely to occur again.

**Comment by aaronmweiss** [comment]
> In my case, I had a large cookie [set by Deluge](https://dev.deluge-torrent.org/ticket/2894). Deleting it resolved the issue. However, it's likely to occur again.
> 
> Edit: Actually, Deluge is not the direct cause. It just happens to create a large cookie.

I deleted my cookies and the Homer worked as expected.

**Comment by jeff-h** [comment]
Same here — in my case I'm running Netdata on a subdomain of the same base domain as Homer, meaning they have the potential to share cookies:

    homer.mydomain.com
    netdata.mydomain.com

Netdata it is setting a huge cookie (~3KB), which causes Homer to throw a 413 error. Deleting the Netdata cookie instantly fixes Homer. Unfortunately it's not this simple though; I tried adding a huge cookie to the Homer demo (https://homer-demo.netlify.app/) and it continued to work just fine. I still can't explain that.

I opened Chrome dev tools and identified one of the resources that was 413'ing; when I tried to access that directly in the browser:

    homer.mydomain.com/js/app.170ffd52.js.map

Nginx displayed an error in the browser (I'm running an nginx reverse proxy); adding `large_client_header_buffers 4 16k;` to my nginx site conf fixed that, but now I get the following in the browser:

    Request Entity Too Large
    Your request was dropped because it was too long.
    Generated by darkhttpd/1.12

![image](https://user-images.githubusercontent.com/841871/116954916-4af52480-ace5-11eb-8a92-fea8f8702f1c.png)

I traced that to [this check](https://github.com/andreasgal/darkhttpd/blob/master/darkhttpd.c#L1959) in darkhttpd; it seems darkhttpd has a hardcoded request limit of 4000 bytes:

```c
/* To prevent a malformed request from eating up too much memory, die once the
 * request exceeds this many bytes:
 */
#define MAX_REQUEST_LENGTH 4000
```

Since it's hardcoded, I'm not seeing much potential to fix this problem in Homer, other than switching to an alternative server?

**Comment by BOZG** [comment]
I had the same issue with Keycloak Gatekeeper. In the process of playing around with OAuth2 Proxy to see if that solve the issue (same error initially), I tested using Redis as a cookie store and so far I've had no issues. I have tried using it with Gatekeeper but might be worth a try.

**Comment by adyanth** [comment]
Same issue with organizr setting a domain wide cookie. Causes the http server to trip. Until I delete the cookie, it won't allow me in.

**Comment by jeryd** [comment]
Fresh install. Same thing happened to me. I have no idea how to fix it.

**Comment by Compizfox** [comment]
Same problem here. It indeed seems to be causes by cookies set by other websites/webapps hosted on the same domain.

For now, I've worked around it by letting Apache (which I'm using as a reverse proxy) remove the cookie header from the request, like this:

```                                                                                                                                                                                                                          
<Location "/homer">                                                                                                                                                                                                                  
        ProxyPass http://localhost:8081                                                                                                                                                                                              
        ProxyPassReverse http://localhost:8081                                                                                                                                                                                       
        RequestHeader unset Cookie                                                                                                                                                                                                   
</Location>
```

I'm sure you can do something similar in other webservers.

**Comment by jeremytodd1** [comment]
I have the same issue pretty often as well. It makes me want to switch back to Heimdall, to be honest. 

I'm hoping this issue gets fixed pretty soon.

**Comment by ibizaman** [comment]
Had this issue with darkhttpd behind keycloak behind haproxy until I replaced darkhttpd with caddy:
```
http://127.0.0.1:8888 {
    root * /opt/homer
	file_server
}
```

**Comment by Kirmy34** [comment]
Any updates on this issue? It's really frustrating...

**Comment by KucharczykL** [comment]
Also just encountered this and deleting cookies helped.

**Comment by Gronda74** [comment]
Same issue here. I'm running a few webapps locally including Homer, tvheadend, emby, and Kavita. Having to delete the cookies every so often is frustrating.

**Comment by bastienwirtz** [comment]
Hi there, Darkhttpd has been replaced by lighttpd and this issue should be fixed!
