### ISSUE TITLE
Avoid adding example configs (and other files) after every start

### ISSUE THREAD

**Issue by RixzZ** [bastienwirtz/homer#209]
I have Homer with a docker volume mounted on '/www/assets' (which seems to be the recommended way to add custom configs).

After I added my config and a folder structure for the images I use, I deleted the rest of the example information that was on that directory. That would be:

- *dist* files
- *sample* files
- *tools* folder

Currently, after every container recreation from the image, that example information gets populated again to the directory, which I would like to avoid.

I see two possible solutions to this:

- Make that the information in that directory is added by the entrypoint script only if there isn't already information there (like when you have mounted a volume with your own config).
- Allow the user to configure an alternative config path (with an ENV variable maybe), so you could use that directory instead and avoid it being modified by the container.

Any thoughts on this?

**Comment by crwallace2** [comment]
If you only want to store the config file externally so you can edit it, you could just mount the config.yml file to the container location for the config.yml, instead of mounting the whole folder. something like the below

`docker run -d \
  --name=homer \
  --restart unless-stopped \
  -p 8080:8080 \
  -e UID=1000 \
  -e GID=1000 \
  -v /vault/homer/config.yml/:/www/assets/config.yml \
  b4bz/homer:latest`

**Comment by bastienwirtz** [comment]
Hi there ! 
Thanks for reporting this. The docker file has been reworked and now you can set the `INIT_ASSETS` env var to 0 to skip default asset install. Hope it helps!
