### ISSUE TITLE
Question : homer/src/components/services/  - scope for home automation ?

### ISSUE THREAD

**Issue by nodecentral** [bastienwirtz/homer#211]
Having very recently enabled the pi-hole service on my Homer dashboard and now seeing the blocking stats come up, it made me wonder where will facility go ?

So far there looks to only be 3 service in the homer/src/components/services/ directory- (AdGuard, Pi-Hole & Generic) but I can see others are being worked on such as ‘open weather’ etc.

Has anyone created anything that supports aspects of home automation? Such as show motion/security sensor statuses, or allow you to turn a light on/off  etc. ?

**Comment by bastienwirtz** [comment]
Hi @nodecentral!

There is not much services for now, but it's definitely an open field! 
An important thing is to keep Homer light & fast, so service should be simple. 

I plan to take time to review & merge the service being worked on soon and add more documentation about creating new services to make it easier for people to contribute, and hopefully more services will be created.

**Comment by nodecentral** [comment]
Thanks for considering it @bastienwirtz 

Having a catalogue of services and ‘tile’ style templates would be a couple of amazing features..

**Comment by trinsic** [comment]
There is definite potential. Grabbing wanted/missing, series count stats for *arr, and download/upload stats from download clients was my goal.

I currently have Sonarr/Radarr/Bazarr showing missing content as well as Pi-Hole showing me actual blocked ads and dns queries since I run a DNS server from there. Whenever it reaches 0 for something it defaults back to the subtitle of the tile.

![Screenshot 2021-05-19 220622](https://user-images.githubusercontent.com/4532152/118837535-1e4d2980-b8ef-11eb-8aa7-52101995644f.jpg)

I wouldn't mind a simple tile showing CPU load, free memory and diskspace. Something on my todo list.
