### ISSUE TITLE
Ability to show content of file

### ISSUE THREAD

**Issue by nh-matti** [bastienwirtz/homer#247]
It would be great not only have the option to parse the jokes of Chuck Norris through the API. Is it possible to show an content of an text file?

`content: $(cat textfile.txt)`

**Comment by bastienwirtz** [comment]
Hi @nh-matti ! 
We can't do that because it's client side web application only. So we can't directly read files from the filesystem. But you can workaround this as it doesn't have to be a real API. You can just add  a `json` file with your content (`{ content: "blablabla" }`) in the asset folder and set the path to this file instead of the Chuck Norris API url. 
Files in the asset folder are served with homer, under the same base URL. 

Could that work for you?

**Comment by nh-matti** [comment]
you're my hero, this works as it should be

**Comment by bastienwirtz** [comment]
I'm glad it worked!
