### ISSUE TITLE
PWA Possibilities

### ISSUE THREAD

**Issue by traeblain** [bastienwirtz/homer#31]
Just adding an issue to start discussion on what to do for a PWA.  

Current thoughts:
- Manifests needs to be static file that contains some data from `config.yml`
- Could have a `pwa: true` tag in config to insert the HEAD LINK tag (use it or not, allows for the simple clone, edit, serve approach).
- Basic bash script (and batch.bat?) that gets the data from `config.yml` and populates manifest (avoiding a build system).  This has the advantage of being a RUN command in Dockerfile (I think).
- Icons...what to do with those (don't you need like 5 different sizes?).

That's a start.  Just throwing it out there for conversation.

**Comment by bastienwirtz** [comment]
Hey @traeblain, 

Thanks for opening the discussion!
That's basically what we need to make it a PWA. As I mentioned before in the other issue, I build homer with a strong commitment to keep it very low maintenance, simple, and just doing the job without having to think about it. Because it's job is to keep your apps on hand, not to add another one. 

That being said, there is a couple of downside: 
* Manually install dependencies makes it more work to update. 
* Service worker [cached file list](https://github.com/bastienwirtz/homer/blob/master/worker.js#L8) is harcoded, have to be updated manually, can easily lead to errors.
* All ressources always keep the same URL, which lead to cache issues (a build system would add a hash to make sure each ressource have a unique URL, ex: `app.js` -> `app-0e89261.js`

So those issue, in addition to the need of something dynamic to have the PWA, makes me reconsider the whole "no build system" policy :thinking:. 

I think I will look into https://parceljs.org/ in the next few days (kinda light & simple alternative to webpack) to see how it could be. 

Any thoughts & ideas warmly welcomed!

**Comment by Joeharrison94** [comment]
I know this isn't the place for this but I just wanted to say I have tried Organizr, Heimdall and Machine Dash and this by far is my favourite frontend app I have used, do you have a sub Reddit or other forum where we can ask for updates / help / showcase Homer more people need to see this imo.

**Comment by Joeharrison94** [comment]
I have some suggestions if your open to feature requests this early on. :) Always up for testing things as well if you need some beta testers

**Comment by bastienwirtz** [comment]
Hey @Joeharrison94! 

Thanks! I'm glad it fits your needs! I don't have a specific sub Reddit or anything for know, I'll think about it. I'm open to ideas and feature requests, feel free to open issues, and have an eye  on the [project philosophy](https://github.com/bastienwirtz/homer/blob/master/CONTRIBUTING.md#project-philosophy) and the [roadmap](https://github.com/bastienwirtz/homer#Roadmap)

I'm currently working on the PWA feature (which makes me add a build system and rework the project like a "real" vuejs app), you will be more than welcome if you want to beta test!

**Comment by Joeharrison94** [comment]
Hell yeah I'd love to beta test, let me know when and what you need

**Comment by bastienwirtz** [comment]
Hi there!

After thinking about this, I choose to go with an easy, efficient and "standard" way to address that: https://github.com/bastienwirtz/homer/pull/62. 

@Joeharrison94 If you still want to beta test things, it would be awesome!

I'm closing this one, we can keep the discussion going on the pull request.
