### ISSUE TITLE
Question: PR with filename change

### ISSUE THREAD

**Issue by gurpal2000** [bastienwirtz/homer#349]
I am working on a PR involving a typo fix for the filename itself "additionnal-page.yml.dist"

The CI/CD fails for my draft PR because it's trying to copy the file from one place to another by the original filename.

Do I give up on the PR or does someone alter the CI/CD. Possible impact ?

thx

**Comment by Roundaround** [comment]
Resolved in #369 and #371 . Closing.

**Comment by gurpal2000** [comment]
My PR came before those contributions. Feels like a stolen PR.

**Comment by Roundaround** [comment]
Don't know why it matters. Your PR got overlooked because the maintainer only had time to review some of the PRs and  he just so happened to see the other one first. Please refrain from spamming other people's PRs and issues complaining about it.

The important part is that the issue got fixed, right? We're all just trying to make the best end result possible!
