### ISSUE TITLE
`You're offline friend.` Error using Homer + Traefik + Google Oauth

### ISSUE THREAD

**Issue by ledicjp** [bastienwirtz/homer#373]
The dashboard shows me the `You're offline friend.` message after about 10 seconds and goes away again after a simple refresh (no cache emptying necessary). Is there a way to disable the Vue alive checker that's doing these checks via a setting? It might have to do something with me using Google Oauth if I understand correctly, but honestly turning it off would be enough for me already. Sorry if this was asked already.

**Comment by fbartels** [comment]
Hi @ledicjp,

you can disable the connectivity check in the configuration https://github.com/bastienwirtz/homer/blob/893690cf95eda1233a094e0d1b63011ff740989e/src/assets/defaults.yml#L11

**Comment by c0pper** [comment]
Where would I find this defaults.yml file if I'm running the docker container version of Homer?

**Comment by c0pper** [comment]
This is the start of my config.yml file, I added the connectivity check line because it wasn't there:
`---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "RaspberryPi di Simone"
subtitle: "Ciao sono il"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
#footer: '<p>Creaated with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a >
**connectivityCheck: false**

# Optional theme customization
`
I restarted the homer container.
Now when i try to access it from my duckdns domain I get this for a brief second and then again "You're offline friend".
![image](https://user-images.githubusercontent.com/18085925/206853985-5db13e02-bd1c-4848-9bf7-6fe7eb8763ce.png)
