### ISSUE TITLE
Ping service adds trailing slash to endpoint URL

### ISSUE THREAD

**Issue by nicoulaj** [bastienwirtz/homer#374]
Using this example config:
```
- name: "Foo"
  type: "Ping"
  url: "https://foo.tld"
  endpoint: "https://foo.tld/health?token=XXXXX"
```

I can see homer sends a request to `https://foo.tld/health?token=XXXXX/`, causing the service to parse the token as `XXXXX/` and return 403.

Tested on version 22.02.1.

**Comment by jamesmacwhite** [comment]
Also confirming the same behaviour, latest docker image.

**Comment by nicoulaj** [comment]
Looks to me like the frontend calls `fetch` with `path= "/"`: https://github.com/bastienwirtz/homer/blob/2fba043575e6a8db94434986c1781d2716c8f6d4/src/components/services/Ping.vue#L32

and `fetch` just concats it with to the endpoint URI:
https://github.com/bastienwirtz/homer/blob/2fba043575e6a8db94434986c1781d2716c8f6d4/src/mixins/service.js#L34

**Comment by jamesmacwhite** [comment]
So the fetch endpoint could do with a similar check with endsWith("/") on the endpoint URL parsing.

The other solution at the moment I can think of is implementing rewrite rules on the endpoint URLs to force them without a trailing slash at the proxy level, until a code fix is implemented.

**Comment by nicoulaj** [comment]
IMHO the best would be not to transform the configured endpoint URL at all, because it will then fail if the service actually requires  a trailing slash... But I am sure there is a good reason for it, maybe @bastienwirtz can step in and give us some insight ?

**Comment by jamesmacwhite** [comment]
Fair point, some may work with the trailing slash added even though it's not what the endpoint value is intended to be, but that's going to vary.

I cloned the source code and locally ran a dev server to mess around with the code. I think the issue is basically with the fetch function as you pointed out.

`${this.endpoint}/${path}` is problematic and it's assuming that path possibly is always populated, so a hard coded / is now in the fetch parameter regardless.

* `${this.endpoint}` - This will either be the `url:` or `endpoint:` value in YAML
* `${path}` - Seems to be null/empty in my tests.

So it's the problem of having `/${path}` appended without checking if ${path} itself has any data I think. Otherwise hard coding a `/` shouldn't happen. I'm not sure exactly where path would get populated though,

**Comment by jamesmacwhite** [comment]
Submitted a PR that should fix this, subject to approval from @bastienwirtz and if I've understood the issue correctly.
