### ISSUE TITLE
Portainer and Adguard custom service not working

### ISSUE THREAD

**Issue by shenhong96** [bastienwirtz/homer#524]
`      - name: "Portainer"
        logo: "assets/tools/Portainer.png"
        type: "Portainer"
        apikey: "MY-API-KEY"
        #tag: "Self-Hosted"
        #tagstyle: "is-warning"
        target: "_blank"
        url: "http://portainer.my-domain.com/"
`

`
      - name: "Adguard Home"
        logo: "assets/tools/Adguard.svg"
        type: "AdGuardHome"
        tag: "Ad-Blocking"
        tagstyle: "is-warning"
        target: "_blank"
        url: "https://adguard.my-domain.com/"
`

Nothing rendered in the homer dashboard and the browser console shows the same error for both domain.
**[Error] Fetch API cannot load https://adguard.my-domain.com/control/status due to access control checks.**

I have the header passed in for both domain through nginx proxy manager.

> `if ($request_method = 'OPTIONS') {
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Credentials' 'true';
    add_header 'Access-Control-Allow-Headers' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';   
    add_header 'Content-Type' 'text/plain; charset=utf-8';
    add_header 'Content-Length' 0;
    return 204;
}
if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
}`

**Comment by shenhong96** [comment]
Some additional info of error
![Uploading image.png…]()

**Comment by impassenet** [comment]
Same problem with portainer.
CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by bastienwirtz** [comment]
Hi there, 

@shenhong96 I think it's because you cannot mix `'Access-Control-Allow-Origin' '*'` and `Access-Control-Allow-Credentials' 'true'`, `*` being too permissive. You can either try to specify the host (`'Access-Control-Allow-Origin' '192.168.9.151:7777'`, and you can add multiples if necessary) or remove the credential: true.

@nikkopt, @impassenet this is a very common issue, have you followed the [troubleshooting guide](https://github.com/bastienwirtz/homer/blob/main/docs/troubleshooting.md) or serach the closed issues? Have you set the correct headers on your services? If headers are correctly set,it will work.

**Comment by nikkopt** [comment]
@bastienwirtz i'm using nginx proxy manager and i've added `'Access-Control-Allow-Origin' '*'` to the configuration of the host. From what i've been told, nginx PM has a bug. I've tried an alternative method which people say it works but it doesn't for me. It will add the header to some files but not to all. `GET piholedomain.com` will get a 404 error because it doesn't have the header. `assets/config.yml` loads fine because it has it and other headers i've added too. I'm clearly doing something wrong or nginx PM isn't working as intended. Anyway, i gave up on custom services..

**Comment by KawaKode** [comment]
Hello,

I managed to make it work, please try this : https://github.com/bastienwirtz/homer/issues/529

Hope it helps :)
