### ISSUE TITLE
CORS Error custom service

### ISSUE THREAD

**Issue by hugomickael** [bastienwirtz/homer#666]
Hi, I have configured homer to connect to all my services, and it is working good with Radarr, Prowlarr, Sonarr, Portainer, but not the other ones using Ping type. It is always showing cors errors:

Access to fetch at 'xxxxxxxxxxxxxxxx' from origin 'yyyyyyyyyyyyy' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I have NPM configured and I added a custom header on custom location "add_header 'Access-Control-Allow-Origin' 'yyyyyyyyyyyyy';", but it is still not working. I also tried the following without success: location / {
   if ($request_method = 'GET') {
    add_header 'Access-Control-Allow-Origin' 'yyyyyyyyyyyyy';
   }
}

Someon has any idea to solve it?

Thanks.

**Comment by mxdanger** [comment]
Make sure you have SSL certificate on dashboard and service. Remove what you added to advanced. Create a custom location and define it as `/` then set the same scheme IP and port already set in details and then click the gear wheel and insert this:

```php
if ($request_method = 'OPTIONS') {
    
add_header 'Access-Control-Allow-Origin' '*';

add_header 'Access-Control-Allow-Credentials' 'true';

add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';

add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,x-api-key';

add_header 'Access-Control-Max-Age' 1728000;

add_header 'Content-Type' 'text/plain charset=UTF-8';

add_header 'Content-Length' 0;

return 204;

}

if ($request_method = 'POST') {

add_header 'Access-Control-Allow-Origin' '*';

add_header 'Access-Control-Allow-Credentials' 'true';

add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';

add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,x-api-key';

}

if ($request_method = 'GET') {

add_header 'Access-Control-Allow-Origin' '*';

add_header 'Access-Control-Allow-Credentials' 'true';

add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';

add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,x-api-key';

}
```

**Comment by Ashkaan** [comment]
Homer is clearly the best dashboard out there, but it's struggling to gain popularity because of all of the CORS issues.  Couldn't you guys integrate something into the app so it works without needing a 3rd party proxy to work correctly?  It's a huge barrier for a lot of folks.  For example, my reverse proxy (Synology DSM 7) doesn't support CORS.

**Comment by bastienwirtz** [comment]
Hello,

Indeed, CORS issue is expected when homer and the target services are on different domain. For the ping cards (or any other service integration) to works, you will require either that:

- All services are exposed on the same domain as homer (mydomain.tld/pihole, mydomain.tld/proxmox), avoiding any cross domain request issues (CORS).
- All services accept cross site requests (= send the necessary CORS headers, either set directly in the service configuration if possible, or using a proxy to set the headers)

@Ashkaan I fully understand. I want to keep Homer a fully front-end app, with no backend required. **BUT** I'm thinking about adding an optional cors proxy that would easy to integrate with homer in the future. 

I'm closing the issue as it's a well known subject, documented, with a lot of possible solution described in past opened issues (feel free to digg into closed issues)

**Comment by mguaylam** [comment]
@bastienwirtz I tried very hard to implement CORS on my proxy but the fact we also need an authentication makes it practically impossible. You would need to handle CORS dynamically to pass thru the auth.

If we want to keep it stricly as a front end, what about providing a separate URL/IP for the APIs? That way I could proxy the API to the same domain and avoid CORS but keep a subdomain format for the access. This would also allow to send APIs calls to a CORS proxy if wanted.

Otherwise, like you said, an optional CORS Proxy. It's definitively more elegant and secure for the secrets but the project then has a back-end indeed.

Unfortunately the fact we have widgets makes it kind of mandatory to have some sort of middle-man with current web security.

**Comment by catrucho** [comment]
@mguaylam I Am facing the same problem . I have all my services on the same machine on docker containers, and I access them with IP:PORT
I installed cors-anywhere in another container to solve it.
I though that there would be a easy way in homer to to config a different IP/URL for the smart card pointing to cors-anywhere proxy with api to see the info, and another one to click and go from the browser. ( apologise for my lack of knowledge and vocabulary on this matter ).
However I read your last message and I realised that there is no way to do so.
I implemented the cors-anywhere solution, now the smartcard, in portainer let's say, is working however when I click in the card in homer, the browser throws the "Missing required request header. Must specify one of: origin,x-requested-with"
I wonder if anyone has been able to solve this problem
