### ISSUE TITLE
Feature Request: Add Login Page to view the Dashboard

### ISSUE THREAD

**Issue by giuliolibrando** [bastienwirtz/homer#728]
Having a login page upfront (even better if connected with an external ldap/active-directory authenticator) would be a great addition for the dashboard. There're cases where not everybody on the network should see the links, even if there's no sensitive data.

**Comment by giuliolibrando** [comment]
Yeah, I know that you can chain projects to obtain the "same" result but a native implementation would be better for everyone

**Comment by nikkopt** [comment]
I don't know if it's feasible. The projects that support that feature natively are huge in comparison, like portainer, nextcloud, grafana, etc. Homer has basically one dev. Also, on some, it's a paid feature.
One thing it can probably be done is to use the Mod auth module on lighttpd. It has basic http auth that is better than nothing. It also has an ldap auth backend. I just don't know if it would make things complex quickly.
You can try editing the lighttpd.conf file and turn on the feature but homer is so small that it might be missing dependencies.

**Comment by zs-dima** [comment]
You can do that by using a reverse proxy and authenticatior, no need to overcomplecate dashboard.

**Comment by Dleewee** [comment]
Apologies if not a good place to ask, but relevant. I have setup homer with Caddy2 (proxy) and Authentik. I was able to redirect users to authenticate with Authentik, but on redirect back to homer around 50% of the time would get a browser download box with the "config.yaml" file instead of the actual webpage. Any thoughts or tips on what's causing that?

**Comment by bastienwirtz** [comment]
@giuliolibrando : As others mentioned, an external auth tool is the way to go with Homer. Homer is simple static HTML and aim to stay that way. There is a lot of alternative out there offering built in authentication is you need it.

@Dleewee That's probably an issue with the cache or the PWA. Once loaded Homer will only do a request for the config.yaml file. Could you configure Authentik to redirect to homer address instead of redirecting to the requested file ?

**Comment by bastienwirtz** [comment]
@Dleewee feel free to open a dediated issue for that if you need. I'm closing this one.
