### ISSUE TITLE
Installing on docker - nothing shows up

### ISSUE THREAD

**Issue by Palshee** [bastienwirtz/homer#73]
Using the provided docker run command, I do not see any files show up in the config or assets folder.

`docker run -p 8080:80 -v /opt/homer/config.yml:/www/config.yml -v /opt/homer/assets/:/www/assets b4bz/homer:latest`

I created the folders manually in this directory:
`/opt/homer/` and `/opt/homer/assets`/

I check the assets folder and its blank.
I created the `config.yml` file and used the template from the main Github page.
I made sure the folders permissions are set correctly as well.
Any idea?

**Comment by ste032** [comment]
I'm a docker beginner but this project challenged the few concepts I thought I understood. 

Anyway, I had the same problem. The` /www/assets` directory inside the container is empty by default (check the Dockerfile) , that's why you didn't find any files in your local dir  `/opt/homer/assets/` either. 

You will have to copy your config.yaml and assets (png icons mostly) inside  `/opt/homer/assets/`  then restart the container.

Hope that helps.

**Comment by Palshee** [comment]
I see. Maybe the docker container could be updated to include what the demo page shows so we have something to go off of

**Comment by bastienwirtz** [comment]
Hi there! 

When using bind mount like this, docker will copy the initial data to the mounted directory. You have to copy it manually. I don't think there is another solution. 

I've updated the documentation with the missing information: https://github.com/bastienwirtz/homer#using-docker, hope it helps!
