### ISSUE TITLE
option to disable connectivity check

### ISSUE THREAD

**Issue by hmoffatt** [bastienwirtz/homer#82]
I'd like to be able to disable the connectivity check from the configuration file. (Due to the configuration of my server, the check fails after a while, even though my connection is just fine.)

**Comment by bastienwirtz** [comment]
Hi there! 

I see, and I agree it's not always useful. I use it because my portal is behind a ssh tunnel, and it make possible for me to know if the tunnel is up before trying to reach any service.

So, there you go: 
```yaml
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)
```
Available in the latest version. Hope that works for you! Thanks for your contribution!

**Comment by hmoffatt** [comment]
Thanks that works great!
