### ISSUE TITLE
Offer a separate container that is not a PWA

### ISSUE THREAD

**Issue by gabe565** [bastienwirtz/homer#95]
Hello!

I'm really enjoying Homer so far, but I'm having trouble with the setup that I usually use. I like to use [Vouch Proxy](https://github.com/vouch/vouch-proxy) to protect internal services from public access, but since this app is a PWA by default, I end up with a white screen until I refresh without cache.

It would be nice if there was a separate Docker image that was not a PWA so that I can follow this standard login process.

**Comment by GlennToms** [comment]
I just use Homer but willing to assist if I can.   It sounds like you have more experience when I do regarding PWAs.
What needs to happen to for a none PWA setup?

**Comment by gabe565** [comment]
I'm still sort of thinking through it all. There might be a better way that I'm not thinking of, but this would be a solution that I could see maybe being useful to some people.

So I know Vue lets you [disable plugins on build](https://cli.vuejs.org/guide/cli-service.html#skipping-plugins) so maybe we could take that as an `ARG` in the Dockerfiles, but I think [this if statement](https://github.com/bastienwirtz/homer/blob/master/src/registerServiceWorker.js#L5) would also have to resolve to `false`.

**Comment by bastienwirtz** [comment]
Hey there!

Thanks for contributing!
I'm curious about the white page issue :thinking: could you provide more information about it?
Otherwise, you might try to empty the `manifest.json` file, or just put an empty json `{}`, I haven't tested it but I think it could disable the PWA feature.

**Comment by gabe565** [comment]
Hello! I'm having this issue because of the way Vouch Proxy works.

It will immediately respond to any request with a 302 to the Oauth2 login endpoint if a user isn't logged in yet (Google in my case). Normally this would redirect me when I hit https://example.com/ and I would login before my browser attempts to load any assets, but with a PWA, all of the html and other static assets get cached client-side. So the only endpoint which actually gets requested is https://example.com/config.yml. Homer does not expect a 302 response and so it just shows a white screen. I'll check to see what the console looks like when this happens.

I tried blocking `service-worker.js` but did not try `manifest.json`. I'll try that now and check back in. Thanks for your response!

**Comment by gabe565** [comment]
I ended up using a [self-destroying service-worker](https://github.com/NekR/self-destroying-sw) and setup a volume bind for that to `/www/service-worker.js` and it seems to be working so far. I'll wait until my session expires and see how well it works. This is a pretty simple solution so hopefully we don't need to build another image!

**Comment by TheTyrius** [comment]
I am also having trouble with the ServiceWorker, because I am using self-signed certificates (and service-workers don't like those). Also what is it required for, because I thought homer was pretty "static"? :)

**Comment by gabe565** [comment]
The service worker is useful for caching assets client-side. This makes the whole site load almost instantly, which is nice since it's meant to be loaded every time you open a new tab or window. Also lets the site work offline, but that's not as useful in this case because then none of the links would work...

That definitely is another reason there should be a flag that disables PWA functionality, though. I'm looking into an elegant way to do it.

**Comment by bastienwirtz** [comment]
I see, thanks for all the feedback. 
A separate container (a tag) build without PWA sounds like a good idea, I'll do that in the near future, and keep this issue updated.

**Comment by bastienwirtz** [comment]
Hey @gabe565 

I've just added redirection handling: https://github.com/bastienwirtz/homer/commit/0ae40f78f837e95ba2ccb04025c6bebcc09d7ab4#diff-ea994a51b0d9884f4fc046eca11a5c99R169

If `config.yml` hits a redirect **and** it's usable (same domain or accepts CORS), the redirection is executed on the global page (the ajax request does not follow the redirect but redirect the whole site).
I haven't tested it with Vouch Proxy yet but I think it should help!

**Comment by gabe565** [comment]
@bastienwirtz That looks great! I'll test it out a little bit later today. Thank you!

**Comment by fbartels** [comment]
> same domain or accepts CORS

is there a specific (technical) reasoning behind this?

I am not using Vouch, but currently have a test setup with https://github.com/Luzifer/nginx-sso/. While being in my company vpn (all traffic is routed through it) I noticed that I first got the "you're offline" notification and then when force reloading I get to  the login page of nginx-sso (which is served by a different subdomain).

I do see requests to `mydomain/homer/assets/img/icons/android-chrome-192x192.png` still getting a "200", while `/homer/assets/config.yml` and `/homer/?alive` produce a ``net::ERR_FAILED`.

PS: I should maybe add that the `ERR_FAILED` is for the redirected url, and directly calling these files gives a 302 like expected.

**Comment by bastienwirtz** [comment]
@fbartels The reason is https://fetch.spec.whatwg.org/#atomic-http-redirect-handling. Doing xhr request to other domain could leak information, so when doing that, it's not possible to get the target URL. The target url is only available when allowed by CORS on the server (`Access-Control-Allow-Origin *` or something like that.). I didn't find any other solution so far. 

in you case the `?alive` request might not be useful (I use it to make sure my ssh tunnel is up) you can disable it `connectivityCheck: false` in the config file. 

Then `config.yml` should be the only file bypassing the cache and triggering the redirect if necessary.

**Comment by fbartels** [comment]
Ah yes, I was not thinking about the fact that all this needs to be triggered through the service worker.

I must say I like the health check and the possibility to show something different when "offline", but with config.yml not being cached anymore some config values are no longer available in this case.

Will have to do some more tests and also extend my nginx-sso configuration to allow the requests from Homer.

**Comment by gabe565** [comment]
So I've been testing this out a bit and for some use-cases I think it will work very well and in some there will still be problems.  
 I tested with a selfhosted Oauth2 provider (I used Nextcloud) and it worked great. But with something like Google or GitHub login, even if I respond with the correct `Access-Control-Allow-Origin` header in Vouch, there's still a redirect to Google's login page which does not have the correct CORS headers.
I could fix that by showing a page with a login button instead of directly redirecting to Google, but I'm already showing a message in Homer if the user is logged out with a link to the login endpoint, so I'll leave that for now.

**Comment by carsso** [comment]
Faced the same issue with the apache mod-auth-openidc (google login handled by apache).
If so, the PWA never refreshes because it does not detect the session has been disconnected, the request is returning a 302 on an external domain (google login) that has not the good CORS headers.

I have disabled the PWA caching feature that (ugly) way :
in precache-manifest.db0fd332c5abac206de452f33be1c39d.js (the db0fd332c5abac206de452f33be1c39d depends of your build) :
`self.__precacheManifest = (self.__precacheManifest || []).concat([]);`

Work like a charm that way, it even detects when you are offline/disconnected from the google account :)

**Comment by Lennart97** [comment]
Hey are there any updates on this?
I just recently discovered this project and love it!
I host it on a VPS with pomerium as my reverse proxy and google oauth. 
After my session expires I'm getting the offline message instead of a redirect to googles login.
On desktop that's not a big deal because I can hard reload with Control + Shift + R and will get the login I  expected.
But that's not possible on my smartphone, so I would love an easy solution to this.

**Comment by Slinky-Wrangle-Punch** [comment]
I think the redirecting based on CORS headers isn't really the best solution.

I would prefer an env variable or a docker flag to disable the serviceworker entirely. The dashboard is so small that I do not care about the additional loading time. However, that it's not loading with an expired auth token is a real deal breaker.

**Comment by funkyfisch** [comment]
I think it is related to my case as well:
I just setup authelia (SSO authenticator) with swag (an nginx + certbot convenience image).
If not logged in, my domain redirects me to authelia for authentication and after a successful login, I am redirected to the /assets/config.yml file. Which triggers a download of the actual config file. Not sure how to tackle the problem here yet.

**Comment by bastienwirtz** [comment]
Hi there! 

Sorry for the long wait on this topic.
I'm closing this one to centralize discussions in the most recent open issue on this: #226. I will work on that asap!

Thanks everyone.
